# -*- coding: utf-8 -*-
"""myproj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNAEf73uoli5SWWzHWqCfc1ImZ-TGH2J
"""

!pip install pandas numpy scikit-learn joblib

!pip install chardet

import kagglehub


path = kagglehub.dataset_download("eswarchandt/phishing-website-detector")

print("Path to dataset files:", path)

import pandas as pd
import joblib
import chardet
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


with open("phishing_data.csv", "rb") as f:
    result = chardet.detect(f.read())

detected_encoding = result["encoding"]
print("Detected Encoding:", detected_encoding)


df = pd.read_csv("phishing_data.csv", encoding=detected_encoding)


X = df.iloc[:, :-1]
y = df.iloc[:, -1]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

joblib.dump(model, "phishing_model.pkl")
print("Model trained & saved successfully!")

import joblib


joblib.dump(model, "phishing_model.pkl")


from google.colab import files
files.download("phishing_model.pkl")

import os
print(os.listdir())

import pandas as pd

file_path = "phishing_data.csv"
df = pd.read_csv(file_path)


df.head()

print(df.columns)

print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


X = df.drop(columns=['class'])
y = df['class']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)